---
# this is used for local development and testing
version: "3.0"
services:
  caddy:
    image: caddy:2.4.6-alpine
    domainname: littlelink-stepan-tech
    container_name: caddy-proxy
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
        - aci-caddy-data:/data
        - caddy:/etc/caddy
    #command: ["caddy", "reverse-proxy", "--from", "littlelink-stepan-tech.westeurope.azurecontainer.io", "--to", "localhost:3000"]
    #command: ["caddy", "reverse-proxy", "--from", "*.stepan.tech", "--to", "localhost:3000"]
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]

  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    #image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
    environment:
      - META_TITLE=Petr Štěpán
      - META_DESCRIPTION=Petr Štěpán Link page
      - META_AUTHOR=Petr Štěpán
      - LANG=en
      - META_INDEX_STATUS=all
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1385949533/ctverec_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1385949533/ctverec_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1385949533/ctverec_400x400.jpg
      - AVATAR_ALT=Petr Štěpán Profile Pic
      - NAME=Petr Štěpán
      - BIO=System Administrator | Scripting Guy | AZURE enthusiast | Apple lover | Biker | NERD
      - FOOTER=Thanks for stopping by!
      - GITHUB=https://github.com/stepantech
      - TWITTER=https://twitter.com/KaoCZ
      - INSTAGRAM=https://www.instagram.com/kaocz
      #- YOUTUBE=https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
      #- TWITCH=https://www.twitch.tv/technotim/
      #- DISCORD=https://l.technotim.live/discord
      #- TIKTOK=https://www.tiktok.com/@technotim
      #- KIT=https://kit.co/TechnoTim
      #- FACEBOOK=https://facebook.com
      #- FACEBOOK_MESSENGER=https://facebook.com
      - LINKED_IN=https://www.linkedin.com/in/petr-stepan/
      #- PRODUCT_HUNT=https://www.producthunt.com/
      #- SNAPCHAT=https://www.snapchat.com/
      #- SPOTIFY=https://www.spotify.com/
      - REDDIT=https://www.reddit.com/user/KaoCZ
      #- MEDIUM=https://medium.com
      #- PINTEREST=https://www.pinterest.com/
      #- EMAIL=you@example.com
      #- EMAIL_TEXT=Email Me!
      #- EMAIL_ALT=you@example.com
      #- EMAIL_ALT_TEXT=Email me!
      #- SOUND_CLOUD=https://soundcloud.com
      #- FIGMA=https://figma.com
      #- TELEGRAM=https://telegram.org/
      #- TUMBLR=https://www.tumblr.com/
      #- STEAM=https://steamcommunity.com/
      #- VIMEO=https://vimeo.com/
      #- WORDPRESS=https://wordpress.com/
      #- GOODREADS=https://www.goodreads.com/
      #- SKOOB=https://www.skoob.com.br/
      #- LETTERBOXD=https://letterboxd.com/
      #- MASTODON=https://mastodon.social/
      #- MICRO_BLOG=https://micro.blog/
      #- WHATSAPP=https://www.whatsapp.com/
      #- STRAVA=https://www.strava.com/
      #- BUYMEACOFFEE=https://www.buymeacoffee.com/
      #- GITLAB=https://www.gitlab.com/
      #- PATREON=https://www.patreon.com/technotim
      #- DEVTO=https://dev.to/
      #- UMAMI_WEBSITE_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #- UMAMI_APP_URL=https://your-umami-app.com
      #- BUTTON_ORDER=YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,DISCORD,FACEBOOK,TIKTOK,KIT,PATREON
      #- PAYPAL=https://www.paypal.me/user
      #- SLACK=https://slack.com/
      #- STACKOVERFLOW=https://stackoverflow.com/
      #- LASTFM=https://last.fm/
      #- GITEA=https://gitea.io/
      #- POLYWORK=https://www.polywork.com/
      #- SIGNAL=https://signal.org/
      #- UNTAPPD=https://untappd.com/
      #- BUTTON_TARGET=_blank
      #- INSTANTGAMING=https://www.instant-gaming.com/
      #- OG_SITE_NAME=Techno Tim Live (OG)
      #- OG_TITLE=Techno Tim (OG)
      #- OG_DESCRIPTION=Techno Tim Link page (OG)
      #- OG_URL=https://technotim.live/
      #- OG_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      #- OG_IMAGE_WIDTH=400
      #- OG_IMAGE_HEIGHT=400
      - TWITTER_CARD=summary_large_image
      - TWITTER_IMAGE=https://pbs.twimg.com/profile_images/1385949533/ctverec_400x400.jpg
      - TWITTER_SITE=@KaoCZ
      - TWITTER_CREATOR=@KaoCZ
    ports:
      - 3000:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  aci-caddy-data:
    driver: azure_file
    driver_opts:
      share_name: aci-caddy-data
      storage_account_name: littlelinksa
  caddy:
    driver: azure_file
    driver_opts:
      share_name: caddy
      storage_account_name: littlelinksa
